import type { Template } from '../../state/useStore'
import type { Theme } from '../../themes'

export function makeRealtyPremiumVariants(theme: Theme): Template[] {
  const BG      = '#0C0C0A'
  const PRIMARY = theme.colors.accent
  const CREAM   = '#F5EDD9'
  const MUTED   = 'rgba(255,255,255,0.25)'
  const HEADING = theme.fonts.heading
  const BODY    = theme.fonts.body

  const rp1x1: Template = {
    id: 'realty-premium-1x1',
    name: 'Realty Premium — 1:1',
    category: 'instagram-post',
    width: 1080,
    height: 1080,
    background: BG,
    elements: [
      { id: 'cat', type: 'text', x: 60, y: 60, width: 600, height: 30,
        props: { text: 'IMOBILIARIA', fontSize: 18, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'left', fill: MUTED, letterSpacing: 5, wrap: 'none' } },
      { id: 'tag-bg', type: 'shape', x: 860, y: 52, width: 160, height: 40,
        props: { fill: 'rgba(200,169,126,0.15)', cornerRadius: 2 } },
      { id: 'tag', type: 'text', x: 860, y: 60, width: 160, height: 26,
        props: { text: 'EXCLUSIVO', fontSize: 16, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'center', fill: PRIMARY, letterSpacing: 3, wrap: 'none' } },
      { id: 'type', type: 'text', x: 60, y: 540, width: 960, height: 30,
        props: { text: 'Apartamento · Bairro', fontSize: 20, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'left', fill: PRIMARY, letterSpacing: 3, wrap: 'none' } },
      { id: 'title', type: 'text', x: 60, y: 590, width: 960, height: 240,
        props: { text: 'Vista panoramica\ne acabamento\nsofisticado', fontSize: 80, fontFamily: HEADING, fontStyle: 'normal', lineHeight: 1.15, align: 'left', fill: CREAM, wrap: 'word', autoFit: true } },
      { id: 'detail1-num', type: 'text', x: 60, y: 860, width: 160, height: 50,
        props: { text: '000m2', fontSize: 36, fontFamily: HEADING, fontStyle: 'bold', lineHeight: 1, align: 'left', fill: PRIMARY, wrap: 'none' } },
      { id: 'detail1-label', type: 'text', x: 60, y: 910, width: 160, height: 26,
        props: { text: 'AREA', fontSize: 16, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'left', fill: MUTED, letterSpacing: 3, wrap: 'none' } },
      { id: 'detail2-num', type: 'text', x: 280, y: 860, width: 160, height: 50,
        props: { text: '0', fontSize: 36, fontFamily: HEADING, fontStyle: 'bold', lineHeight: 1, align: 'left', fill: PRIMARY, wrap: 'none' } },
      { id: 'detail2-label', type: 'text', x: 280, y: 910, width: 160, height: 26,
        props: { text: 'SUITES', fontSize: 16, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'left', fill: MUTED, letterSpacing: 3, wrap: 'none' } },
      { id: 'detail3-num', type: 'text', x: 500, y: 860, width: 160, height: 50,
        props: { text: '0', fontSize: 36, fontFamily: HEADING, fontStyle: 'bold', lineHeight: 1, align: 'left', fill: PRIMARY, wrap: 'none' } },
      { id: 'detail3-label', type: 'text', x: 500, y: 910, width: 160, height: 26,
        props: { text: 'VAGAS', fontSize: 16, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'left', fill: MUTED, letterSpacing: 3, wrap: 'none' } },
      { id: 'divider', type: 'shape', x: 60, y: 970, width: 960, height: 1,
        props: { fill: '#1A1A14', cornerRadius: 0 } },
      { id: 'price', type: 'text', x: 60, y: 990, width: 600, height: 40,
        props: { text: 'R$ 0.000.000', fontSize: 32, fontFamily: HEADING, fontStyle: 'normal', lineHeight: 1, align: 'left', fill: CREAM, wrap: 'none' } },
      { id: 'cta', type: 'text', x: 800, y: 996, width: 220, height: 30,
        props: { text: 'AGENDAR VISITA', fontSize: 16, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'right', fill: PRIMARY, letterSpacing: 2, wrap: 'none' } },
    ],
  }

  const rp4x5: Template = {
    id: 'realty-premium-4x5',
    name: 'Realty Premium — 4:5',
    category: 'instagram-post',
    width: 1080,
    height: 1350,
    background: BG,
    elements: [
      { id: 'cat', type: 'text', x: 60, y: 80, width: 600, height: 30,
        props: { text: 'IMOBILIARIA', fontSize: 18, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'left', fill: MUTED, letterSpacing: 5, wrap: 'none' } },
      { id: 'tag-bg', type: 'shape', x: 860, y: 72, width: 160, height: 40,
        props: { fill: 'rgba(200,169,126,0.15)', cornerRadius: 2 } },
      { id: 'tag', type: 'text', x: 860, y: 80, width: 160, height: 26,
        props: { text: 'EXCLUSIVO', fontSize: 16, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'center', fill: PRIMARY, letterSpacing: 3, wrap: 'none' } },
      { id: 'type', type: 'text', x: 60, y: 740, width: 960, height: 30,
        props: { text: 'Apartamento · Bairro', fontSize: 20, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'left', fill: PRIMARY, letterSpacing: 3, wrap: 'none' } },
      { id: 'title', type: 'text', x: 60, y: 790, width: 960, height: 240,
        props: { text: 'Vista panoramica\ne acabamento\nsofisticado', fontSize: 80, fontFamily: HEADING, fontStyle: 'normal', lineHeight: 1.15, align: 'left', fill: CREAM, wrap: 'word', autoFit: true } },
      { id: 'detail1-num', type: 'text', x: 60, y: 1070, width: 160, height: 50,
        props: { text: '000m2', fontSize: 36, fontFamily: HEADING, fontStyle: 'bold', lineHeight: 1, align: 'left', fill: PRIMARY, wrap: 'none' } },
      { id: 'detail1-label', type: 'text', x: 60, y: 1120, width: 160, height: 26,
        props: { text: 'AREA', fontSize: 16, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'left', fill: MUTED, letterSpacing: 3, wrap: 'none' } },
      { id: 'detail2-num', type: 'text', x: 280, y: 1070, width: 160, height: 50,
        props: { text: '0', fontSize: 36, fontFamily: HEADING, fontStyle: 'bold', lineHeight: 1, align: 'left', fill: PRIMARY, wrap: 'none' } },
      { id: 'detail2-label', type: 'text', x: 280, y: 1120, width: 160, height: 26,
        props: { text: 'SUITES', fontSize: 16, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'left', fill: MUTED, letterSpacing: 3, wrap: 'none' } },
      { id: 'detail3-num', type: 'text', x: 500, y: 1070, width: 160, height: 50,
        props: { text: '0', fontSize: 36, fontFamily: HEADING, fontStyle: 'bold', lineHeight: 1, align: 'left', fill: PRIMARY, wrap: 'none' } },
      { id: 'detail3-label', type: 'text', x: 500, y: 1120, width: 160, height: 26,
        props: { text: 'VAGAS', fontSize: 16, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'left', fill: MUTED, letterSpacing: 3, wrap: 'none' } },
      { id: 'divider', type: 'shape', x: 60, y: 1240, width: 960, height: 1,
        props: { fill: '#1A1A14', cornerRadius: 0 } },
      { id: 'price', type: 'text', x: 60, y: 1260, width: 600, height: 40,
        props: { text: 'R$ 0.000.000', fontSize: 32, fontFamily: HEADING, fontStyle: 'normal', lineHeight: 1, align: 'left', fill: CREAM, wrap: 'none' } },
      { id: 'cta', type: 'text', x: 800, y: 1266, width: 220, height: 30,
        props: { text: 'AGENDAR VISITA', fontSize: 16, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'right', fill: PRIMARY, letterSpacing: 2, wrap: 'none' } },
    ],
  }

  const rp9x16: Template = {
    id: 'realty-premium-9x16',
    name: 'Realty Premium — 9:16',
    category: 'instagram-story',
    width: 1080,
    height: 1920,
    background: BG,
    elements: [
      { id: 'cat', type: 'text', x: 60, y: 120, width: 600, height: 30,
        props: { text: 'IMOBILIARIA', fontSize: 20, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'left', fill: MUTED, letterSpacing: 5, wrap: 'none' } },
      { id: 'tag-bg', type: 'shape', x: 860, y: 112, width: 160, height: 40,
        props: { fill: 'rgba(200,169,126,0.15)', cornerRadius: 2 } },
      { id: 'tag', type: 'text', x: 860, y: 120, width: 160, height: 26,
        props: { text: 'EXCLUSIVO', fontSize: 16, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'center', fill: PRIMARY, letterSpacing: 3, wrap: 'none' } },
      { id: 'type', type: 'text', x: 60, y: 1100, width: 960, height: 30,
        props: { text: 'Apartamento · Bairro', fontSize: 22, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'left', fill: PRIMARY, letterSpacing: 3, wrap: 'none' } },
      { id: 'title', type: 'text', x: 60, y: 1160, width: 960, height: 340,
        props: { text: 'Vista panoramica\ne acabamento\nsofisticado', fontSize: 100, fontFamily: HEADING, fontStyle: 'normal', lineHeight: 1.15, align: 'left', fill: CREAM, wrap: 'word', autoFit: true } },
      { id: 'detail1-num', type: 'text', x: 60, y: 1560, width: 200, height: 60,
        props: { text: '000m2', fontSize: 40, fontFamily: HEADING, fontStyle: 'bold', lineHeight: 1, align: 'left', fill: PRIMARY, wrap: 'none' } },
      { id: 'detail1-label', type: 'text', x: 60, y: 1620, width: 200, height: 30,
        props: { text: 'AREA', fontSize: 18, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'left', fill: MUTED, letterSpacing: 3, wrap: 'none' } },
      { id: 'detail2-num', type: 'text', x: 340, y: 1560, width: 200, height: 60,
        props: { text: '0', fontSize: 40, fontFamily: HEADING, fontStyle: 'bold', lineHeight: 1, align: 'left', fill: PRIMARY, wrap: 'none' } },
      { id: 'detail2-label', type: 'text', x: 340, y: 1620, width: 200, height: 30,
        props: { text: 'SUITES', fontSize: 18, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'left', fill: MUTED, letterSpacing: 3, wrap: 'none' } },
      { id: 'detail3-num', type: 'text', x: 620, y: 1560, width: 200, height: 60,
        props: { text: '0', fontSize: 40, fontFamily: HEADING, fontStyle: 'bold', lineHeight: 1, align: 'left', fill: PRIMARY, wrap: 'none' } },
      { id: 'detail3-label', type: 'text', x: 620, y: 1620, width: 200, height: 30,
        props: { text: 'VAGAS', fontSize: 18, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'left', fill: MUTED, letterSpacing: 3, wrap: 'none' } },
      { id: 'divider', type: 'shape', x: 60, y: 1740, width: 960, height: 1,
        props: { fill: '#1A1A14', cornerRadius: 0 } },
      { id: 'price', type: 'text', x: 60, y: 1760, width: 600, height: 50,
        props: { text: 'R$ 0.000.000', fontSize: 36, fontFamily: HEADING, fontStyle: 'normal', lineHeight: 1, align: 'left', fill: CREAM, wrap: 'none' } },
      { id: 'cta', type: 'text', x: 760, y: 1766, width: 260, height: 40,
        props: { text: 'AGENDAR VISITA', fontSize: 18, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'right', fill: PRIMARY, letterSpacing: 2, wrap: 'none' } },
    ],
  }

  const rp16x9: Template = {
    id: 'realty-premium-16x9',
    name: 'Realty Premium — 16:9',
    category: 'linkedin-banner',
    width: 1920,
    height: 1080,
    background: BG,
    elements: [
      { id: 'cat', type: 'text', x: 100, y: 60, width: 600, height: 30,
        props: { text: 'IMOBILIARIA', fontSize: 20, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'left', fill: MUTED, letterSpacing: 5, wrap: 'none' } },
      { id: 'tag-bg', type: 'shape', x: 1700, y: 52, width: 160, height: 40,
        props: { fill: 'rgba(200,169,126,0.15)', cornerRadius: 2 } },
      { id: 'tag', type: 'text', x: 1700, y: 60, width: 160, height: 26,
        props: { text: 'EXCLUSIVO', fontSize: 16, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'center', fill: PRIMARY, letterSpacing: 3, wrap: 'none' } },
      { id: 'type', type: 'text', x: 100, y: 380, width: 800, height: 30,
        props: { text: 'Apartamento · Bairro', fontSize: 20, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'left', fill: PRIMARY, letterSpacing: 3, wrap: 'none' } },
      { id: 'title', type: 'text', x: 100, y: 430, width: 800, height: 340,
        props: { text: 'Vista panoramica\ne acabamento\nsofisticado', fontSize: 90, fontFamily: HEADING, fontStyle: 'normal', lineHeight: 1.15, align: 'left', fill: CREAM, wrap: 'word', autoFit: true } },
      { id: 'detail1-num', type: 'text', x: 1060, y: 380, width: 200, height: 60,
        props: { text: '000m2', fontSize: 40, fontFamily: HEADING, fontStyle: 'bold', lineHeight: 1, align: 'left', fill: PRIMARY, wrap: 'none' } },
      { id: 'detail1-label', type: 'text', x: 1060, y: 440, width: 200, height: 30,
        props: { text: 'AREA', fontSize: 18, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'left', fill: MUTED, letterSpacing: 3, wrap: 'none' } },
      { id: 'detail2-num', type: 'text', x: 1340, y: 380, width: 200, height: 60,
        props: { text: '0', fontSize: 40, fontFamily: HEADING, fontStyle: 'bold', lineHeight: 1, align: 'left', fill: PRIMARY, wrap: 'none' } },
      { id: 'detail2-label', type: 'text', x: 1340, y: 440, width: 200, height: 30,
        props: { text: 'SUITES', fontSize: 18, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'left', fill: MUTED, letterSpacing: 3, wrap: 'none' } },
      { id: 'detail3-num', type: 'text', x: 1620, y: 380, width: 200, height: 60,
        props: { text: '0', fontSize: 40, fontFamily: HEADING, fontStyle: 'bold', lineHeight: 1, align: 'left', fill: PRIMARY, wrap: 'none' } },
      { id: 'detail3-label', type: 'text', x: 1620, y: 440, width: 200, height: 30,
        props: { text: 'VAGAS', fontSize: 18, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'left', fill: MUTED, letterSpacing: 3, wrap: 'none' } },
      { id: 'divider', type: 'shape', x: 100, y: 860, width: 1720, height: 1,
        props: { fill: '#1A1A14', cornerRadius: 0 } },
      { id: 'price', type: 'text', x: 100, y: 880, width: 800, height: 50,
        props: { text: 'R$ 0.000.000', fontSize: 36, fontFamily: HEADING, fontStyle: 'normal', lineHeight: 1, align: 'left', fill: CREAM, wrap: 'none' } },
      { id: 'cta', type: 'text', x: 1600, y: 886, width: 260, height: 40,
        props: { text: 'AGENDAR VISITA', fontSize: 18, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'right', fill: PRIMARY, letterSpacing: 2, wrap: 'none' } },
    ],
  }

  return [rp1x1, rp4x5, rp9x16, rp16x9]
}
