import type { Template } from '../../state/useStore'
import type { Theme } from '../../themes'

export function makeRealtyLaunchVariants(theme: Theme): Template[] {
  const BG      = '#FFFFFF'
  const PRIMARY = theme.colors.accent
  const DARK    = '#1A1A2E'
  const MUTED   = '#999999'
  const WHITE   = '#FFFFFF'
  const HEADING = theme.fonts.heading
  const BODY    = theme.fonts.body

  const rl1x1: Template = {
    id: 'realty-launch-1x1',
    name: 'Realty Launch — 1:1',
    category: 'instagram-post',
    width: 1080,
    height: 1080,
    background: BG,
    elements: [
      { id: 'cat', type: 'text', x: 60, y: 60, width: 600, height: 30,
        props: { text: 'IMOBILIARIA', fontSize: 18, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'left', fill: MUTED, letterSpacing: 5, wrap: 'none' } },
      { id: 'badge-bg', type: 'shape', x: 840, y: 52, width: 180, height: 40,
        props: { fill: DARK, cornerRadius: 2 } },
      { id: 'badge', type: 'text', x: 840, y: 60, width: 180, height: 26,
        props: { text: 'LANCAMENTO', fontSize: 16, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'center', fill: WHITE, letterSpacing: 3, wrap: 'none' } },
      { id: 'tag', type: 'text', x: 60, y: 340, width: 960, height: 30,
        props: { text: 'NOVO EMPREENDIMENTO', fontSize: 18, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'left', fill: DARK, letterSpacing: 5, wrap: 'none' } },
      { id: 'title', type: 'text', x: 60, y: 390, width: 960, height: 340,
        props: { text: 'NOME DO\nEMPREEN\nDIMENTO', fontSize: 130, fontFamily: HEADING, fontStyle: 'bold', lineHeight: 0.95, align: 'left', fill: DARK, wrap: 'word', autoFit: true } },
      { id: 'spec1-bar', type: 'shape', x: 60, y: 770, width: 4, height: 50,
        props: { fill: PRIMARY, cornerRadius: 0 } },
      { id: 'spec1-val', type: 'text', x: 76, y: 772, width: 160, height: 30,
        props: { text: '00m2', fontSize: 26, fontFamily: HEADING, fontStyle: 'bold', lineHeight: 1, align: 'left', fill: DARK, wrap: 'none' } },
      { id: 'spec1-lab', type: 'text', x: 76, y: 802, width: 160, height: 22,
        props: { text: 'AREA', fontSize: 14, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'left', fill: MUTED, letterSpacing: 2, wrap: 'none' } },
      { id: 'spec2-bar', type: 'shape', x: 300, y: 770, width: 4, height: 50,
        props: { fill: PRIMARY, cornerRadius: 0 } },
      { id: 'spec2-val', type: 'text', x: 316, y: 772, width: 160, height: 30,
        props: { text: '0-0', fontSize: 26, fontFamily: HEADING, fontStyle: 'bold', lineHeight: 1, align: 'left', fill: DARK, wrap: 'none' } },
      { id: 'spec2-lab', type: 'text', x: 316, y: 802, width: 160, height: 22,
        props: { text: 'QUARTOS', fontSize: 14, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'left', fill: MUTED, letterSpacing: 2, wrap: 'none' } },
      { id: 'spec3-bar', type: 'shape', x: 540, y: 770, width: 4, height: 50,
        props: { fill: PRIMARY, cornerRadius: 0 } },
      { id: 'spec3-val', type: 'text', x: 556, y: 772, width: 160, height: 30,
        props: { text: '0000', fontSize: 26, fontFamily: HEADING, fontStyle: 'bold', lineHeight: 1, align: 'left', fill: DARK, wrap: 'none' } },
      { id: 'spec3-lab', type: 'text', x: 556, y: 802, width: 160, height: 22,
        props: { text: 'ENTREGA', fontSize: 14, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'left', fill: MUTED, letterSpacing: 2, wrap: 'none' } },
      { id: 'divider', type: 'shape', x: 60, y: 920, width: 960, height: 1,
        props: { fill: '#EEEEEE', cornerRadius: 0 } },
      { id: 'price', type: 'text', x: 60, y: 940, width: 600, height: 50,
        props: { text: 'A partir de R$ 000k', fontSize: 32, fontFamily: HEADING, fontStyle: 'bold', lineHeight: 1, align: 'left', fill: DARK, wrap: 'none' } },
      { id: 'cta-bg', type: 'shape', x: 800, y: 934, width: 220, height: 46,
        props: { fill: DARK, cornerRadius: 2 } },
      { id: 'cta', type: 'text', x: 800, y: 946, width: 220, height: 26,
        props: { text: 'SAIBA MAIS', fontSize: 16, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'center', fill: WHITE, letterSpacing: 3, wrap: 'none' } },
    ],
  }

  const rl4x5: Template = {
    id: 'realty-launch-4x5',
    name: 'Realty Launch — 4:5',
    category: 'instagram-post',
    width: 1080,
    height: 1350,
    background: BG,
    elements: [
      { id: 'cat', type: 'text', x: 60, y: 80, width: 600, height: 30,
        props: { text: 'IMOBILIARIA', fontSize: 18, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'left', fill: MUTED, letterSpacing: 5, wrap: 'none' } },
      { id: 'badge-bg', type: 'shape', x: 840, y: 72, width: 180, height: 40,
        props: { fill: DARK, cornerRadius: 2 } },
      { id: 'badge', type: 'text', x: 840, y: 80, width: 180, height: 26,
        props: { text: 'LANCAMENTO', fontSize: 16, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'center', fill: WHITE, letterSpacing: 3, wrap: 'none' } },
      { id: 'tag', type: 'text', x: 60, y: 500, width: 960, height: 30,
        props: { text: 'NOVO EMPREENDIMENTO', fontSize: 18, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'left', fill: DARK, letterSpacing: 5, wrap: 'none' } },
      { id: 'title', type: 'text', x: 60, y: 550, width: 960, height: 340,
        props: { text: 'NOME DO\nEMPREEN\nDIMENTO', fontSize: 130, fontFamily: HEADING, fontStyle: 'bold', lineHeight: 0.95, align: 'left', fill: DARK, wrap: 'word', autoFit: true } },
      { id: 'spec1-bar', type: 'shape', x: 60, y: 1000, width: 4, height: 50,
        props: { fill: PRIMARY, cornerRadius: 0 } },
      { id: 'spec1-val', type: 'text', x: 76, y: 1002, width: 160, height: 30,
        props: { text: '00m2', fontSize: 26, fontFamily: HEADING, fontStyle: 'bold', lineHeight: 1, align: 'left', fill: DARK, wrap: 'none' } },
      { id: 'spec1-lab', type: 'text', x: 76, y: 1032, width: 160, height: 22,
        props: { text: 'AREA', fontSize: 14, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'left', fill: MUTED, letterSpacing: 2, wrap: 'none' } },
      { id: 'spec2-bar', type: 'shape', x: 300, y: 1000, width: 4, height: 50,
        props: { fill: PRIMARY, cornerRadius: 0 } },
      { id: 'spec2-val', type: 'text', x: 316, y: 1002, width: 160, height: 30,
        props: { text: '0-0', fontSize: 26, fontFamily: HEADING, fontStyle: 'bold', lineHeight: 1, align: 'left', fill: DARK, wrap: 'none' } },
      { id: 'spec2-lab', type: 'text', x: 316, y: 1032, width: 160, height: 22,
        props: { text: 'QUARTOS', fontSize: 14, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'left', fill: MUTED, letterSpacing: 2, wrap: 'none' } },
      { id: 'spec3-bar', type: 'shape', x: 540, y: 1000, width: 4, height: 50,
        props: { fill: PRIMARY, cornerRadius: 0 } },
      { id: 'spec3-val', type: 'text', x: 556, y: 1002, width: 160, height: 30,
        props: { text: '0000', fontSize: 26, fontFamily: HEADING, fontStyle: 'bold', lineHeight: 1, align: 'left', fill: DARK, wrap: 'none' } },
      { id: 'spec3-lab', type: 'text', x: 556, y: 1032, width: 160, height: 22,
        props: { text: 'ENTREGA', fontSize: 14, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'left', fill: MUTED, letterSpacing: 2, wrap: 'none' } },
      { id: 'divider', type: 'shape', x: 60, y: 1180, width: 960, height: 1,
        props: { fill: '#EEEEEE', cornerRadius: 0 } },
      { id: 'price', type: 'text', x: 60, y: 1200, width: 600, height: 50,
        props: { text: 'A partir de R$ 000k', fontSize: 32, fontFamily: HEADING, fontStyle: 'bold', lineHeight: 1, align: 'left', fill: DARK, wrap: 'none' } },
      { id: 'cta-bg', type: 'shape', x: 800, y: 1194, width: 220, height: 46,
        props: { fill: DARK, cornerRadius: 2 } },
      { id: 'cta', type: 'text', x: 800, y: 1206, width: 220, height: 26,
        props: { text: 'SAIBA MAIS', fontSize: 16, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'center', fill: WHITE, letterSpacing: 3, wrap: 'none' } },
    ],
  }

  const rl9x16: Template = {
    id: 'realty-launch-9x16',
    name: 'Realty Launch — 9:16',
    category: 'instagram-story',
    width: 1080,
    height: 1920,
    background: BG,
    elements: [
      { id: 'cat', type: 'text', x: 60, y: 120, width: 600, height: 30,
        props: { text: 'IMOBILIARIA', fontSize: 20, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'left', fill: MUTED, letterSpacing: 5, wrap: 'none' } },
      { id: 'badge-bg', type: 'shape', x: 840, y: 112, width: 180, height: 40,
        props: { fill: DARK, cornerRadius: 2 } },
      { id: 'badge', type: 'text', x: 840, y: 120, width: 180, height: 26,
        props: { text: 'LANCAMENTO', fontSize: 16, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'center', fill: WHITE, letterSpacing: 3, wrap: 'none' } },
      { id: 'tag', type: 'text', x: 60, y: 800, width: 960, height: 30,
        props: { text: 'NOVO EMPREENDIMENTO', fontSize: 20, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'left', fill: DARK, letterSpacing: 5, wrap: 'none' } },
      { id: 'title', type: 'text', x: 60, y: 860, width: 960, height: 440,
        props: { text: 'NOME DO\nEMPREEN\nDIMENTO', fontSize: 160, fontFamily: HEADING, fontStyle: 'bold', lineHeight: 0.95, align: 'left', fill: DARK, wrap: 'word', autoFit: true } },
      { id: 'spec1-bar', type: 'shape', x: 60, y: 1420, width: 4, height: 60,
        props: { fill: PRIMARY, cornerRadius: 0 } },
      { id: 'spec1-val', type: 'text', x: 76, y: 1422, width: 200, height: 36,
        props: { text: '00m2', fontSize: 30, fontFamily: HEADING, fontStyle: 'bold', lineHeight: 1, align: 'left', fill: DARK, wrap: 'none' } },
      { id: 'spec1-lab', type: 'text', x: 76, y: 1460, width: 200, height: 26,
        props: { text: 'AREA', fontSize: 16, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'left', fill: MUTED, letterSpacing: 2, wrap: 'none' } },
      { id: 'spec2-bar', type: 'shape', x: 380, y: 1420, width: 4, height: 60,
        props: { fill: PRIMARY, cornerRadius: 0 } },
      { id: 'spec2-val', type: 'text', x: 396, y: 1422, width: 200, height: 36,
        props: { text: '0-0', fontSize: 30, fontFamily: HEADING, fontStyle: 'bold', lineHeight: 1, align: 'left', fill: DARK, wrap: 'none' } },
      { id: 'spec2-lab', type: 'text', x: 396, y: 1460, width: 200, height: 26,
        props: { text: 'QUARTOS', fontSize: 16, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'left', fill: MUTED, letterSpacing: 2, wrap: 'none' } },
      { id: 'spec3-bar', type: 'shape', x: 700, y: 1420, width: 4, height: 60,
        props: { fill: PRIMARY, cornerRadius: 0 } },
      { id: 'spec3-val', type: 'text', x: 716, y: 1422, width: 200, height: 36,
        props: { text: '0000', fontSize: 30, fontFamily: HEADING, fontStyle: 'bold', lineHeight: 1, align: 'left', fill: DARK, wrap: 'none' } },
      { id: 'spec3-lab', type: 'text', x: 716, y: 1460, width: 200, height: 26,
        props: { text: 'ENTREGA', fontSize: 16, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'left', fill: MUTED, letterSpacing: 2, wrap: 'none' } },
      { id: 'divider', type: 'shape', x: 60, y: 1700, width: 960, height: 1,
        props: { fill: '#EEEEEE', cornerRadius: 0 } },
      { id: 'price', type: 'text', x: 60, y: 1720, width: 600, height: 50,
        props: { text: 'A partir de R$ 000k', fontSize: 34, fontFamily: HEADING, fontStyle: 'bold', lineHeight: 1, align: 'left', fill: DARK, wrap: 'none' } },
      { id: 'cta-bg', type: 'shape', x: 800, y: 1714, width: 220, height: 52,
        props: { fill: DARK, cornerRadius: 2 } },
      { id: 'cta', type: 'text', x: 800, y: 1728, width: 220, height: 28,
        props: { text: 'SAIBA MAIS', fontSize: 18, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'center', fill: WHITE, letterSpacing: 3, wrap: 'none' } },
    ],
  }

  const rl16x9: Template = {
    id: 'realty-launch-16x9',
    name: 'Realty Launch — 16:9',
    category: 'linkedin-banner',
    width: 1920,
    height: 1080,
    background: BG,
    elements: [
      { id: 'cat', type: 'text', x: 100, y: 60, width: 600, height: 30,
        props: { text: 'IMOBILIARIA', fontSize: 20, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'left', fill: MUTED, letterSpacing: 5, wrap: 'none' } },
      { id: 'badge-bg', type: 'shape', x: 1680, y: 52, width: 180, height: 40,
        props: { fill: DARK, cornerRadius: 2 } },
      { id: 'badge', type: 'text', x: 1680, y: 60, width: 180, height: 26,
        props: { text: 'LANCAMENTO', fontSize: 16, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'center', fill: WHITE, letterSpacing: 3, wrap: 'none' } },
      { id: 'tag', type: 'text', x: 100, y: 320, width: 800, height: 30,
        props: { text: 'NOVO EMPREENDIMENTO', fontSize: 20, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'left', fill: DARK, letterSpacing: 5, wrap: 'none' } },
      { id: 'title', type: 'text', x: 100, y: 370, width: 800, height: 380,
        props: { text: 'NOME DO\nEMPREENDIMENTO', fontSize: 130, fontFamily: HEADING, fontStyle: 'bold', lineHeight: 0.95, align: 'left', fill: DARK, wrap: 'word', autoFit: true } },
      { id: 'spec1-bar', type: 'shape', x: 1060, y: 320, width: 4, height: 60,
        props: { fill: PRIMARY, cornerRadius: 0 } },
      { id: 'spec1-val', type: 'text', x: 1076, y: 322, width: 200, height: 36,
        props: { text: '00m2', fontSize: 30, fontFamily: HEADING, fontStyle: 'bold', lineHeight: 1, align: 'left', fill: DARK, wrap: 'none' } },
      { id: 'spec1-lab', type: 'text', x: 1076, y: 360, width: 200, height: 26,
        props: { text: 'AREA', fontSize: 16, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'left', fill: MUTED, letterSpacing: 2, wrap: 'none' } },
      { id: 'spec2-bar', type: 'shape', x: 1360, y: 320, width: 4, height: 60,
        props: { fill: PRIMARY, cornerRadius: 0 } },
      { id: 'spec2-val', type: 'text', x: 1376, y: 322, width: 200, height: 36,
        props: { text: '0-0', fontSize: 30, fontFamily: HEADING, fontStyle: 'bold', lineHeight: 1, align: 'left', fill: DARK, wrap: 'none' } },
      { id: 'spec2-lab', type: 'text', x: 1376, y: 360, width: 200, height: 26,
        props: { text: 'QUARTOS', fontSize: 16, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'left', fill: MUTED, letterSpacing: 2, wrap: 'none' } },
      { id: 'spec3-bar', type: 'shape', x: 1660, y: 320, width: 4, height: 60,
        props: { fill: PRIMARY, cornerRadius: 0 } },
      { id: 'spec3-val', type: 'text', x: 1676, y: 322, width: 200, height: 36,
        props: { text: '0000', fontSize: 30, fontFamily: HEADING, fontStyle: 'bold', lineHeight: 1, align: 'left', fill: DARK, wrap: 'none' } },
      { id: 'spec3-lab', type: 'text', x: 1676, y: 360, width: 200, height: 26,
        props: { text: 'ENTREGA', fontSize: 16, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'left', fill: MUTED, letterSpacing: 2, wrap: 'none' } },
      { id: 'divider', type: 'shape', x: 100, y: 860, width: 1720, height: 1,
        props: { fill: '#EEEEEE', cornerRadius: 0 } },
      { id: 'price', type: 'text', x: 100, y: 880, width: 800, height: 50,
        props: { text: 'A partir de R$ 000k', fontSize: 36, fontFamily: HEADING, fontStyle: 'bold', lineHeight: 1, align: 'left', fill: DARK, wrap: 'none' } },
      { id: 'cta-bg', type: 'shape', x: 1660, y: 874, width: 220, height: 52,
        props: { fill: DARK, cornerRadius: 2 } },
      { id: 'cta', type: 'text', x: 1660, y: 888, width: 220, height: 28,
        props: { text: 'SAIBA MAIS', fontSize: 18, fontFamily: BODY, fontStyle: 'normal', lineHeight: 1, align: 'center', fill: WHITE, letterSpacing: 3, wrap: 'none' } },
    ],
  }

  return [rl1x1, rl4x5, rl9x16, rl16x9]
}
